from exercise.common import show_title

# 内置函数
show_title('内置函数')
print("__import__()", '内置的导入函数')
print("abs()", '计算绝对值', abs(-123))
print("all()", '所有的迭代之都=True')
print("any()", '任何=True，则返回True')
print("ascii()", '返回ascii码')
print("bin()", '转换二进制')
print("bool()", '转换bool类型')
print("bytearray()", '转换bytearray')
print("bytes()", '转换bytes')
print("callable()", '返回True如果对象参数出现可调用， False如果没有。')
print("chr()", '返回表示其Unicode代码点是整数i的字符的字符串')
print("classmethod()", '返回函数的类方法')
print("compile()", '将源代码编译为代码或AST对象。代码对象可以由exec()或执行eval()')
print("complex()", '返回值为real + imag * 1j的复数')
print("delattr()", '删除属性值')
print("dict()", "转换字典", dict({'a': 1, 'b': 2}))
print("dir()", '查询对象的方法、属性')
print("divmod()", '函数把除数和余数运算结果结合起来,返回一个包含商和余数的元组(a // b, a % b)')
print("enumerate()", '返回枚举对象')
print("eval()", '运行程序代码')
print("exec()", '执行外部程序')
print("filter()", '过滤数据，filter（function，iterable ）')
print("float()", '转换float')
print("format()", '格式化数据，一般转换为对象的format函数调用')
print("frozenset()", '返回一个新的frozenset对象')
print("getattr()", '返回属性值')
print("globals()", '返回所有的全局对象')
print("hasattr()", '判断是否有属性')
print("hash()", '返回对象的hash值')
print("help()", '生成帮助', help('sys.os'))
print("hex()", '转换16进制')
print("id()", '返回对象的唯一id', id(list()))
print("input()", '接受用户的输入值')
print("int()", '返回整数值')
print("isinstance()", '判断是否是一个实例对象')
print("issubclass()", '是否子类的判断语句')
print("iter()", '返回一个迭代对象')
print("len()", '返回长度')
print("list()", '转换list')
print("locals()", '查看本地对象')
print("map()", '返回一个迭代器，将函数应用于每个可迭代项，产生结果')
print("max()", '最大值')
print("memoryview()", )
print("min()", '最小值', min([1, 2, 3]))
print("next()", '下一个迭代值')
print("object()", '返回一个新对象', 'c=object()')
print("oct()", '八进制值')
print("open()", '打开文件')
print("ord()", '返回一个表示该字符的Unicode代码点的整数')
print("pow()", '返回x到幂y')
print("print()", '打印结果')
print("property()", '返回属性')
print("range()", '范围函数，range(start, stop[, step])')
print("repr()", '返回对象的字符串值，对应__repr__()方法')
print("reversed()", '对象翻转')
print("round()", '取整')
print("set()", 'Return a new set object')
print("setattr()", '设置属性值')
print("slice()", '返回一个切片对象，类似data[1:3]')
print("sorted()", '排序对象')
print("staticmethod()", '使用@staticmethod转换为静态方法')
print("str()", '转换字符串')
print("sum()", '合计')
print("super()", '父类')
print("tuple()", '元组')
print("type()", '查看类型')
print("vars()", '返回对象object的属性和属性值的字典对象')
print("zip()", 'zip() 函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的列表')
print('\n' * 2)

# 函数定义
show_title('函数定义')


# 定义函数
def fun1(a, b=1):
    print(a, b)


# 定义拼合参数的函数
def fun2(id=1, *a, **b):
    print('id=', id, 'a=', a, 'b=', b)
    for x in a: print(x)


fun1(1, 2)
fun1(b=2, a=1)
fun1(1, b=2)
fun1(*(1, 2))
fun1(12)
fun2(1, 2, 3, name='tom', age=20)
